// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppLogPath() {
  return window['go']['main']['App']['AppLogPath']();
}

export function Busy() {
  return window['go']['main']['App']['Busy']();
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function ConsoleMode() {
  return window['go']['main']['App']['ConsoleMode']();
}

export function DiskUsageDirect(arg1) {
  return window['go']['main']['App']['DiskUsageDirect'](arg1);
}

export function ExportAppLog() {
  return window['go']['main']['App']['ExportAppLog']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Info() {
  return window['go']['main']['App']['Info']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function ReadCleanLog() {
  return window['go']['main']['App']['ReadCleanLog']();
}

export function RunAdvanced(arg1) {
  return window['go']['main']['App']['RunAdvanced'](arg1);
}

export function RunDisk(arg1) {
  return window['go']['main']['App']['RunDisk'](arg1);
}

export function RunLarge(arg1) {
  return window['go']['main']['App']['RunLarge'](arg1);
}

export function RunQuick() {
  return window['go']['main']['App']['RunQuick']();
}

export function SetSettings(arg1, arg2) {
  return window['go']['main']['App']['SetSettings'](arg1, arg2);
}
