// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppLogPath():Promise<string>;

export function Busy():Promise<boolean>;

export function Cancel():Promise<{[key: string]: any}>;

export function ConsoleMode():Promise<{[key: string]: any}>;

export function DiskUsageDirect(arg1:string):Promise<{[key: string]: any}>;

export function ExportAppLog():Promise<{[key: string]: any}>;

export function GetSettings():Promise<main.Settings>;

export function Info():Promise<{[key: string]: any}>;

export function OpenPath(arg1:string):Promise<string>;

export function ReadCleanLog():Promise<{[key: string]: any}>;

export function RunAdvanced(arg1:Array<string>):Promise<{[key: string]: any}>;

export function RunDisk(arg1:string):Promise<{[key: string]: any}>;

export function RunLarge(arg1:string):Promise<{[key: string]: any}>;

export function RunQuick():Promise<{[key: string]: any}>;

export function SetSettings(arg1:boolean,arg2:string):Promise<main.Settings>;
